// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvKjG5ucOvfmj4W_wg0pnCxBCc7v0SuoE',
    appId: '1:996327499755:web:b9a4a53886a38b06cadbae',
    messagingSenderId: '996327499755',
    projectId: 'flutter-module-2-9d4a1',
    authDomain: 'flutter-module-2-9d4a1.firebaseapp.com',
    storageBucket: 'flutter-module-2-9d4a1.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiBda3uPq1yVDxjB4jrMRl86ivojbtXSw',
    appId: '1:996327499755:ios:8fa3ad78998fcabbcadbae',
    messagingSenderId: '996327499755',
    projectId: 'flutter-module-2-9d4a1',
    storageBucket: 'flutter-module-2-9d4a1.firebasestorage.app',
    iosBundleId: 'com.example.flutterModule2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvKjG5ucOvfmj4W_wg0pnCxBCc7v0SuoE',
    appId: '1:996327499755:web:7c1434896ce3b1edcadbae',
    messagingSenderId: '996327499755',
    projectId: 'flutter-module-2-9d4a1',
    authDomain: 'flutter-module-2-9d4a1.firebaseapp.com',
    storageBucket: 'flutter-module-2-9d4a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiBda3uPq1yVDxjB4jrMRl86ivojbtXSw',
    appId: '1:996327499755:ios:8fa3ad78998fcabbcadbae',
    messagingSenderId: '996327499755',
    projectId: 'flutter-module-2-9d4a1',
    storageBucket: 'flutter-module-2-9d4a1.firebasestorage.app',
    iosBundleId: 'com.example.flutterModule2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKp1WWffOt-2IT8CK3K1ti3x72L3kA7fE',
    appId: '1:996327499755:android:8ca3b5587ffc1843cadbae',
    messagingSenderId: '996327499755',
    projectId: 'flutter-module-2-9d4a1',
    storageBucket: 'flutter-module-2-9d4a1.firebasestorage.app',
  );

}